---
title: "Fiscales"
author: "Oscar Velazco"
format: html
editor: visual
---
```{r}
install.packages(c("rio", "tidyverse", "writexl"))
```
```{r}
library(rio)
library(tidyverse)
library (ggplot2)
library(dplyr)
library(writexl)
library(tidyr)
library(stringr)
```

# Importamos y unimos las bases de datos

```{r}
#Añadimos la base de datos de FISCALES
Fiscales_2019 = import("BD-fiscales-2019.csv")
Fiscales_2020 = import("BD-fiscales-2020.csv")
Fiscales_2021 = import("BD-fiscales-2021.csv")
Fiscales_2022 = import("BD-fiscales-2022.csv")
Fiscales_2023 = import("BD-fiscales-2023.csv")
Fiscales_2024 = import("BD-fiscales-2024.csv")
Fiscales_2025 = import("BD-fiscales-2025-12.csv")

fiscales_total <- bind_rows(Fiscales_2019, Fiscales_2020, Fiscales_2021, Fiscales_2022, Fiscales_2023, Fiscales_2024, Fiscales_2025)
```
##Filtrando
```{r}
unique(fiscales_seleccion$ubicacion_especialidad)
```
```{r}
fiscales_anticorrupcion <- fiscales_seleccion %>%
  filter(ubicacion_especialidad == "CORRUPCION DE FUNCIONARIOS")
```
##Dataframe limpio
```{r}
fiscales_anticorrupcion <- subset(
  fiscales_total,
  ubicacion_especialidad == "CORRUPCION DE FUNCIONARIOS" & anio >= 2019 & anio <= 2025,
  select = c(anio, cargo, condicion, sexo, total, ubicacion_especialidad)
)
```
